import { Hex } from "../types";
export type Response = "hex" | "bytes";
export declare function bytesToHex(bytes: Uint8Array): string;
export declare function hexToBytes(hex: string, hexadecimal?: boolean): Uint8Array;
export declare function sha256(message: Uint8Array, hash256?: boolean): Uint8Array;
export declare function hash256(message: Uint8Array): Uint8Array;
export declare function ripemd160(message: Uint8Array, address?: boolean): Uint8Array;
export declare function checksum(message: Uint8Array, bytes?: number): Uint8Array;
export declare function reverseEndian(hex: Hex): Hex;
export declare function numberToHex(number?: number, bits?: number): Uint8Array;
export declare function numberToHexLE(number?: number, bits?: number): Uint8Array;
export declare function hash160ToScript(hash160: Hex): Hex;
export declare function reverseHexLE(hex: Hex, isBytes?: boolean): Hex;
export declare function mergeUint8Arrays(...arrays: Uint8Array[]): Uint8Array;
export declare function isEqual(...arrays: Uint8Array[]): boolean;
export declare function numberToVarTnt(value: number): Uint8Array;
export declare function getBytesCount(hex: string): number;
